const std = @import("std");

pub fn main() !void {
    const allocator = std.heap.page_allocator;

    const out = try std.fs.cwd().createFile("src/bun_ffi/types.zig", .{});
    defer out.close();

    var writer = out.writer().any();

    try writer.writeAll(
        \\// This file is generated by write_general_tests.zig.
    ,
        .{},
    );
}
