
// This file is auto-generated by @chainsafe/bun-ffi-z. Do not edit.

import path from "node:path";
import { openLibrary } from "@chainsafe/bun-ffi-z";

const fns = {
  "pool_init": {
    "args": [
      "u32"
    ],
    "returns": "u32"
  },
  "pool_deinit": {
    "args": [],
    "returns": "void"
  },
  "node_ref": {
    "args": [
      "u32"
    ],
    "returns": "u32"
  },
  "node_unref": {
    "args": [
      "u32"
    ],
    "returns": "void"
  },
  "node_get_root": {
    "args": [
      "u32",
      "ptr"
    ],
    "returns": "void"
  },
  "node_get_node": {
    "args": [
      "u32",
      "u32"
    ],
    "returns": "i32"
  },
  "node_get_left": {
    "args": [
      "u32"
    ],
    "returns": "i32"
  },
  "node_get_right": {
    "args": [
      "u32"
    ],
    "returns": "i32"
  },
  "phase0_checkpoint_create_default_tree": {
    "args": [],
    "returns": "i32"
  }
} as const;
const lib = await openLibrary(path.join(import.meta.dirname, ".."), fns);

export const binding = lib.symbols;
export const close = lib.close;

