name: Zig Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zig-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: "0.13.0" # Set the required Zig version

      - name: Build and Unit Test
        run: |
          zig build test:unit
      - name: Lodestar Test
        run: |
          zig build test:lodestar

      - name: Build and Integration Test
        run: |
          zig build test:int
