name: Zig Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zig-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: "0.13.0" # Set the required Zig version

      - name: persistent-merkle-tree - build and unit test
        working-directory: packages/persistent-merkle-tree
        run: |
          zig build test:unit

      - name: ssz - build and unit test
        working-directory: packages/ssz
        run: |
          zig build test:unit
      - name: ssz - lodestar test
        working-directory: packages/ssz
        run: |
          zig build test:lodestar
      - name: ssz - build and integration test
        working-directory: packages/ssz
        run: |
          zig build test:int
